//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateExchangeApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRatesLog
    {
        public int Id { get; set; }
        public string RequestedURL { get; set; }
        public string OperationType { get; set; }
        public string CurrencyFrom { get; set; }
        public string CurrencyTo { get; set; }
        public Nullable<decimal> ValueInput { get; set; }
        public Nullable<decimal> ValueOutput { get; set; }
        public string Exception { get; set; }
    }
}
